#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import string
import random
import sys

low_set = string.ascii_letters
medium_set = low_set + string.digits
high_set = medium_set + '!@#$%^&*()'


def show_help():
    "Show the help message"

    help_message = """
    Usage: python3 password.py [strength] [length]

    Example
        python3 password.py high 32
        python3 password.py low 8
    """

    sys.stdout.write(help_message)
    sys.exit()


def low_strength(length):
    password = random.sample(low_set, length)
    return "".join(password)


def medium_strength(length):
    password = random.sample(medium_set, length)
    return "".join(password)


def high_strength(length):
    password = random.sample(high_set, length)
    return "".join(password)


def main():
    try:
        if any(x in sys.argv[1] for x in ['low', 'weak']):
            sys.stdout.write(low_strength(int(sys.argv[2])))
        elif any(x in sys.argv[1] for x in ['medium', 'average']):
            sys.stdout.write(medium_strength(int(sys.argv[2])))
        elif any(x in sys.argv[1] for x in ['high', 'hard']):
            sys.stdout.write(high_strength(int(sys.argv[2])))
    except:
        show_help()

main()
sys.exit()
